language: python
sudo: false
cache: pip
branches:
  only:
    - master

matrix:
  include:
  - python: 2.7
    env: TOXENV=py27
  - python: pypy
    env: TOXENV=pypy
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 2.7
    env: TOXENV=flake8
install:
  # Upgrade packaging tools separately, so that other installations are
  # performed with the upgraded tools.
  - pip install -U pip setuptools wheel
  - pip install tox codecov
  - |
    if [ "${TOXENV::5}" == "pypy-" ]; then
      git clone --depth 1 https://github.com/yyuu/pyenv.git ~/.pyenv
      PYENV_ROOT="$HOME/.pyenv"
      PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv install pypy-5.4.1
      pyenv global pypy-5.4.1
    fi

script:
  - tox

after_success:
  # Codecov needs combined coverage, and having the raw report in the test
  # output can be useful.
  - tox -e coverage-report
  - codecov

notifications:
  email: false
